
# Site settings

# NB! Set your site's url, otherwise stuff will break :)

url: "https://aaroncrobinson.github.io/"

# Google tracking id

google-tracking-id: "UA-105317243-1"

# Forces https everywhere in your website, except when you serve it locally
# If you are not hosted on Github Pages, and your host doesn't support https
# then you should disable it

force-https: True

#############
# HTML Head #
#############

lang: "en"
author: "Aaron C Robinson"
title: "Aaron.C.Robinson"
description: "Blog and website of John Smith, blogging mainly for tech. Opinions expressed are mine."
keywords: "aaroncrobinson, aarobrobinson, robinson, aaron, rimworld"
favicon: "/img/logo_square.ico"

################
# Header layout #
################

black-favicon: "/img/logo_small.ico"

background-img: "../img/intro-bg.jpg"

##############################
# Dynamic Text on the Header #
##############################

dynamic-typing: True
shuffle: True # Shuffle the lines.
loop: True
loop-count: False # Set False for infinite loop, or set any number for finite loop.
type-speed: 50
backspace-speed: 30
start-delay: 0
delete-delay: 5000
fadeout: True
fadeout-delay: 2500
fadeout-speed: .5s
lines: # You can add HTML Tags in the Text
  - text: "If you build it,^250 they will come."
  - text: "Give me a fulcrum,^350 <br> and I shall move the world."
  - text: "If at first the idea is not absurd,^500 <br>  then there is no hope for it."
  - text: "If numbers aren't beautiful,^400 <br>  I don't know what is."
  - text: "True knowledge exists in knowing^150 <br> that you know nothing."
  - text: "An unexamined life is not worth living."

me-img: "/img/author.jpg"

# To use github profile pic uncomment the following line and replace 'user_name'
# with your github user name.

# me-img: "https://github.com/user_name.png?size=500"

# To use gravatar profile pic uncomment the following line and replace 'email_hash'
# with your gravatar profile email hash.
# You can create the email hash by using an online tool like 'http://www.md5hashgenerator.com/'
# just enter your email and it will generate the hash.

# me-img: "https://www.gravatar.com/avatar/email_hash?s=500"

##############################
# Color the browser elements #
##############################
color-browser: "#000000"
apple-status-bar-style: "black"

################
# Web app mode #
################

web-app-mode: True

# Icons for Web App mode

icon-36p: "/img/web-app/icon-36p.png"
icon-48p: "/img/web-app/icon-48p.png"
icon-72p: "/img/web-app/icon-72p.png"
icon-96p: "/img/web-app/icon-96p.png"
icon-144p: "/img/web-app/icon-144p.png"
icon-192p: "/img/web-app/icon-192p.png"

########
# Blog #
########

enable-gesture-navigation: True

post-preview-words: 96

paginate: 5

email-share: True
fb-share: False
twitter-share: True
linkedin-share: True
reddit-share: True
google-plus-share: True
tumblr-share: True
pinterest-share: True
pocket-share: True
vkontakte-share: True

disqus-shortname: "aaroncrobinson"

syntax-highlight: True

############
# Timeline #
############

events:
  - image: "/img/timeline/spidertocat.png"
    date: "September 2013 - Today"
    description: "Saving the neighborhood!"
  - image: "/img/timeline/baracktocat.jpg"
    date: "September 2007 - August 2013"
    description: "Started coding"

# First image of the Timeline

timeline-img: "/img/timeline/default.png"

################
# Author Blurb #
################

# The author blurb goes underneath blog posts.
# This works best when your author blurb image has a transparent background, or matches your site background color.

# if the author_blurb is not set, then this feature is skipped
author_blurb: "Aaron Robinson is a wonderer and a wanderer."
author_blurb_image: "/img/author.jpg"

##################
# Social Buttons #
##################

social:
  - title: "github"
    url: "https://github.com/AaronCRobinson"
#  - title: "bitcoin"
#    url: "https://blockchain.info/address/1LHuKC9Em3KA5yoZaf7nngnNdf9K7s2gSi"
  - title: "rss"
    url: "/feed.xml"

############
# 404 page #
############

err-404-img: "/img/labtocat.png"

##################
# GPG on Keybase #
##################

keybase-username: aaroncrobinson
keybase-in-social: False
keybase-in-footer: True

#################
# Resume and CV #
#################

resume: http://aaroncrobinson.x10host.com/resume.pdf
cv: http://aaroncrobinson.x10host.com/cv.pdf

################################################################################

# NB! Tread carefully if you want to change the variables below this point!

# Sections shown in the index page

pages_list:
  About: 'about'
#  Blog: 'latest-post'
  Projects: 'projects'
#  Timeline: 'timeline'
  Contact: 'contact'

# Exclusion list from the generated _site

exclude: ["LICENSE", "README.md", "CONTRIBUTING", "CONTRIBUTORS", "scripts"]

# Pagination path

paginate_path: "blog/page:num/"

# Enable minification SASS

sass:
  style: compressed

plugins:
  - jekyll-paginate
  - jemoji
